### ISSUE TITLE
Error in nested queries

### ISSUE THREAD

**Issue by rasca** [KristianOellegaard/django-hvad#241]
While attempting to upgrade https://github.com/rasca/django-taggit-hvad to the latest hvad I've encountered an error introduced in hvad 0.5

The code affected is https://github.com/rasca/django-taggit-hvad/blob/c4a16483e0278b4d10f05dd828f6a2fd58da1ef7/taggit/managers.py#L195

When running the tests, upgrading to hvad==0.5.2 (I'm upgrading for one hvad version at a time) I get
```
======================================================================
ERROR: test_add_tag (taggit.tests.tests.TaggableManagerCustomPKTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/ivan/Sites/django-taggit/taggit/tests/tests.py", line 135, in test_add_tag
    apple.tags.remove('green')
  File "/home/ivan/Sites/django-taggit/taggit/utils.py", line 125, in inner
    return func(self, *args, **kwargs)
  File "/home/ivan/Sites/django-taggit/taggit/managers.py", line 196, in remove
    self.through.objects.filter(**self._lookup_kwargs()).filter(
  File "/home/ivan/Sites/django-taggit/bootstrap/local/lib/python2.7/site-packages/django/db/models/query.py", line 500, in delete
    del_query = self._clone()
  File "/home/ivan/Sites/django-taggit/bootstrap/local/lib/python2.7/site-packages/django/db/models/query.py", line 873, in _clone
    query = self.query.clone()
  File "/home/ivan/Sites/django-taggit/bootstrap/local/lib/python2.7/site-packages/django/db/models/sql/query.py", line 259, in clone
    obj.where = copy.deepcopy(self.where, memo=memo)
  File "/usr/lib/python2.7/copy.py", line 174, in deepcopy
    y = copier(memo)
  File "/home/ivan/Sites/django-taggit/bootstrap/local/lib/python2.7/site-packages/django/utils/tree.py", line 61, in __deepcopy__
    obj.children = copy.deepcopy(self.children, memodict)
  File "/usr/lib/python2.7/copy.py", line 163, in deepcopy
    y = copier(x, memo)
  File "/usr/lib/python2.7/copy.py", line 230, in _deepcopy_list
    y.append(deepcopy(a, memo))
  File "/usr/lib/python2.7/copy.py", line 174, in deepcopy
    y = copier(memo)
  File "/home/ivan/Sites/django-taggit/bootstrap/local/lib/python2.7/site-packages/django/utils/tree.py", line 61, in __deepcopy__
    obj.children = copy.deepcopy(self.children, memodict)
  File "/usr/lib/python2.7/copy.py", line 163, in deepcopy
    y = copier(x, memo)
  File "/usr/lib/python2.7/copy.py", line 230, in _deepcopy_list
    y.append(deepcopy(a, memo))
  File "/usr/lib/python2.7/copy.py", line 163, in deepcopy
    y = copier(x, memo)
  File "/usr/lib/python2.7/copy.py", line 237, in _deepcopy_tuple
    y.append(deepcopy(a, memo))
  File "/usr/lib/python2.7/copy.py", line 174, in deepcopy
    y = copier(memo)
  File "/home/ivan/Sites/django-taggit/bootstrap/local/lib/python2.7/site-packages/django/db/models/query.py", line 52, in __deepcopy__
    obj = self.__class__()
TypeError: __init__() takes at least 2 arguments (1 given)
```

This happens because Django internally deepcopies the queryset and does it by creating a new queryset instance and then deepcopy each element in the original queryset `__dict__`

The error was introduced in this commit / line by requesting the `model` arg:
https://github.com/KristianOellegaard/django-hvad/commit/e321603780e7892b05fc545e83e2ce5c1a4f76c5#diff-0cf33a7dbdaa950dd5ad761ad4c4dbe5R108

**Comment by rasca** [comment]
BTW I'm using Django 1.4 upgrading everything to 1.8 LTS.

This also happens in several places in my project.

**Comment by spectras** [comment]
Hello,

The structure of hvad-generated models hasn't changed so you can go straight to the latest version.
That will not fix your issue though. The place you linked in the code should be modified.
The call is a bit messy as some third-party application pass the model through kwargs, and others as a positioned argument. Both must work.

I'll look into it tomorrow. Better than doing it wrong now (it's late here).

**Comment by spectras** [comment]
By the way, the trigger for this, is a bug that was present up to (but not including) Django version 1.6.
The implementation of nester queries triggered a large deepcopy of a lot of unneeded objects that caused some bugs and had a significant performance impact.

It turns out that the TranslatableQueryset gets included in the pack of unneeded objects, and that uses its `__deepcopy__` method, which in turns triggers the issue you found with the constructor making the model argument mandatory.

Upgrading to Django 1.6 should remove the Django bug that triggers this hvad bug. And this hvad bug  should be fixed on master, now, and will be part of a corrective 1.2.1 release in a couple of days.

Do you need the fix to be backported to some older release as well?

**Comment by rasca** [comment]
Hello,

Thank you very much for the fix! I'm upgrading to the latest hvad, so no backport needed here.

I take this opportunity to also thank you for the excellent job you've been doing with hvad since you take over the project. I've been following hvad's development from when it was nani and your work here is an example on how to support an open source app!

**Comment by spectras** [comment]
Hi again,

Sorry for answering a bit late. I barely found the time to release last week. I hope it fixed your issue and you could complete your migration.
Thanks for reporting, and thanks for your comment, it's great knowing the work is appreciated. I mostly have the download counts, but they're much less expressive than actual words :)
