### ISSUE TITLE
`unique` and `unique_together` in `TranslatedFields`

### ISSUE THREAD

**Issue by barseghyanartur** [KristianOellegaard/django-hvad#244]
How to use `unique` and `unique_together` in `TranslatedFields`?

I know that `master` and `language` are already unique together.

Case 1:

I want `slug` to be `unique` (for the language).

    class Camping1(TranslatableModel):
        translations = TranslatedFields(
            name = models.CharField(max_length=255),
            slug = models.SlugField(max_length=255),
        )

Case 2:

I want `slug` and `code` to be `unique_together` (for the language).

    class Camping1(TranslatableModel):
        translations = TranslatedFields(
            name = models.CharField(max_length=255),
            slug = models.SlugField(max_length=255),
            code = models.CharField(max_length=10)
        )

**Comment by spectras** [comment]
Hello barseghyanartur,
I'm not home right now, so I cannot check but I believe you should be able to do this:
```python
class Camping1(TranslatableModel):
    translations = TranslatedFields(
        name = models.CharField(max_length=255),
        slug = models.SlugField(max_length=255),
        code = models.CharField(max_length=10)
    )
    class Meta:
        unique_together = [('slug', 'code', 'language_code')]
```
Can you try that and tell me if it works?

**Comment by barseghyanartur** [comment]
@spectras: 


    """
    Traceback (most recent call last):
      File "./manage.py", line 11, in <module>
        execute_from_command_line(sys.argv)
      File "/home/user/.envs/myenv/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 385, in execute_from_command_line
        utility.execute()
      File "/home/user/.envs/myenv/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 354, in execute
        django.setup()
      File "/home/user/.envs/myenv/local/lib/python2.7/site-packages/django/__init__.py", line 21, in setup
        apps.populate(settings.INSTALLED_APPS)
      File "/home/user/.envs/myenv/local/lib/python2.7/site-packages/django/apps/registry.py", line 108, in populate
        app_config.import_models(all_models)
      File "/home/user/.envs/myenv/local/lib/python2.7/site-packages/django/apps/config.py", line 202, in import_models
        self.models_module = import_module(models_module_name)
      File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
        __import__(name)
      File "/home/artur/gitrepos/vacansoleil/vs-django-cms/servicebus/models.py", line 282, in <module>
        class AbstractFacility(TranslatableModel):
      File "/home/user/.envs/myenv/local/lib/python2.7/site-packages/django/db/models/base.py", line 168, in __new__
        new_class.add_to_class(obj_name, obj)
      File "/home/user/.envs/myenv/local/lib/python2.7/site-packages/django/db/models/base.py", line 297, in add_to_class
        value.contribute_to_class(cls, name)
      File "/home/user/.envs/myenv/local/lib/python2.7/site-packages/hvad/models.py", line 172, in contribute_to_class
        create_translations_model(cls, name, self.meta, **self.fields)
      File "/home/user/.envs/myenv/local/lib/python2.7/site-packages/hvad/models.py", line 106, in create_translations_model
        sconst, tconst = _split_together(model._meta.unique_together, fields, meta, 'unique_together')
      File "/home/user/.envs/myenv/local/lib/python2.7/site-packages/hvad/models.py", line 52, in _split_together
        'untranslated fields, such as %r.' % (name, constraint))
    django.core.exceptions.ImproperlyConfigured: Constraints in Meta.unique_together cannot mix translated and untranslated fields, such as ('slug', 'language_code').
    """

**Comment by spectras** [comment]
Hmmm, looks like I did not account for the possiblity of including `language_code`.
I'll have a look right now.

**Comment by spectras** [comment]
Fixed on main branch. I'll release it soon, but I'd like to investigate your other issue first.

**Comment by barseghyanartur** [comment]
@spectras:

Thank you!

**Comment by spectras** [comment]
You're welcome.
I'm waiting for travis to run all tests before pushing the release to PyPI.
It appears they're having some issues that delay tests for some reason. I'll post here again when it's ready.

**Comment by spectras** [comment]
Fix should be available on PyPI, as django-hvad version 1.2.2.

**Comment by barseghyanartur** [comment]
@spectras:

Awesome! Thank you very much.

**Comment by frontendr** [comment]
Hi @spectras,

It seems to be working indeed but when I add a `unique_together` like this:
```
    translations = TranslatedFields(
        title=models.CharField(_('titel'), max_length=255),
        slug=models.SlugField(_('slug'), max_length=255),
        meta={'unique_together': [('slug', 'language_code')]},
    )
```

I get a IntegrityError error screen when saving a model with a duplicate slug in the admin. Is there any way this can be fixed so the user gets a proper validation error instead of an error 500?

The error:
```
IntegrityError at /nl/admin/timeline/exhibition/add/
(1062, "Duplicate entry 'test-nl' for key 'timeline_exhibition_translation_slug_29de5faf6ce732b8_uniq'")
```

**Comment by spectras** [comment]
@frontends As it is a different issue, I moved it into its own entry, #251.
