### ISSUE TITLE
how can solve this error for django hvad in django-cms

### ISSUE THREAD

**Issue by kartikdanidhariya** [KristianOellegaard/django-hvad#286]
i configure django-cms in ubuntu version are

django-cms==3.2.3
django-hvad==1.5.0

in degree application it return error like 

hvad.exceptions.Wrongmanager: To access translated fields like 'slug' from an untranslated model,you must use a translation aware manager.for non-translatable models, you can get one using hvad.utills.get_translation_aware_manager.
for translatable models, use the language() method. 

how can i solve this error plz help!!

**Comment by spectras** [comment]
Hello,

Can you post the whole error trace please? It is required to pinpoint the issue.

**Comment by kartikdanidhariya** [comment]
whole error trace is


Unhandled exception in thread started by <function wrapper at 0x7f471df28320>
Traceback (most recent call last):
  File "/root/dev/myenv/local/lib/python2.7/site-packages/django/utils/autoreload.py", line 226, in wrapper
    fn(*args, **kwargs)
  File "/root/dev/myenv/local/lib/python2.7/site-packages/django/core/management/commands/runserver.py", line 109, in inner_run
    autoreload.raise_last_exception()
  File "/root/dev/myenv/local/lib/python2.7/site-packages/django/utils/autoreload.py", line 249, in raise_last_exception
    six.reraise(*_exception)
  File "/root/dev/myenv/local/lib/python2.7/site-packages/django/utils/autoreload.py", line 226, in wrapper
    fn(*args, **kwargs)
  File "/root/dev/myenv/local/lib/python2.7/site-packages/django/__init__.py", line 18, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/root/dev/myenv/local/lib/python2.7/site-packages/django/apps/registry.py", line 115, in populate
    app_config.ready()
  File "/root/dev/myenv/local/lib/python2.7/site-packages/django/contrib/admin/apps.py", line 22, in ready
    self.module.autodiscover()
  File "/root/dev/myenv/local/lib/python2.7/site-packages/django/contrib/admin/__init__.py", line 26, in autodiscover
    autodiscover_modules('admin', register_to=site)
  File "/root/dev/myenv/local/lib/python2.7/site-packages/django/utils/module_loading.py", line 50, in autodiscover_modules
    import_module('%s.%s' % (app_config.name, module_to_search))
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/root/dev/demo/domain/admin.py", line 56, in <module>
    admin.site.register(Domain, DomainAdmin)
  File "/root/dev/myenv/local/lib/python2.7/site-packages/django/contrib/admin/sites.py", line 109, in register
    system_check_errors.extend(admin_obj.check())
  File "/root/dev/myenv/local/lib/python2.7/site-packages/django/contrib/admin/options.py", line 113, in check
    return self.checks_class().check(self, **kwargs)
  File "/root/dev/myenv/local/lib/python2.7/site-packages/django/contrib/admin/checks.py", line 495, in check
    errors = super(ModelAdminChecks, self).check(admin_obj)
  File "/root/dev/myenv/local/lib/python2.7/site-packages/django/contrib/admin/checks.py", line 35, in check
    errors.extend(self._check_prepopulated_fields(admin_obj))
  File "/root/dev/myenv/local/lib/python2.7/site-packages/django/contrib/admin/checks.py", line 350, in _check_prepopulated_fields
    for field_name, val in obj.prepopulated_fields.items()
  File "/root/dev/myenv/local/lib/python2.7/site-packages/django/contrib/admin/checks.py", line 365, in _check_prepopulated_fields_key
    field = model._meta.get_field(field_name)
  File "/root/dev/myenv/local/lib/python2.7/site-packages/hvad/utils.py", line 139, in __call__
    "method." % name)
hvad.exceptions.WrongManager: To access translated fields like 'slug' from an untranslated model, you must use a translation aware manager. For non-translatable models, you can get one using hvad.utils.get_translation_aware_manager.
For translatable models, use the language() method.

**Comment by spectras** [comment]
Hello again. Sorry for the delay.
So from what I understand, this error arises when you start the application?
It looks you are using the `slug` field, which is translated, in some place where it is not supported by the admin application. Did you write a custom admin ? If so, could you look for places where you use `slug` and post them as well?

It is frustrating, because Django admin is paranoiac and tends to abort when it detects conditions that would have worked, if it were not for the startup check. I think it might be one of those cases.

**Comment by spectras** [comment]
Closing due to inactivity. Feel free to re-open if needed :)
