### ISSUE TITLE
django 1.10 ValueError: max() arg is an empty sequence

### ISSUE THREAD

**Issue by spaceexperiment** [KristianOellegaard/django-hvad#306]
Using django 1.10 and djang-hvad https://github.com/kristianoellegaard/django-hvad/tarball/master, 
when running makemigrations i am getting this.

```Traceback (most recent call last):
  File "manage.py", line 22, in <module>
    execute_from_command_line(sys.argv)
  File "/Users/jibl/.Envs/eduwallets/lib/python3.5/site-packages/django/core/management/__init__.py", line 367, in execute_from_command_line
    utility.execute()
  File "/Users/jibl/.Envs/eduwallets/lib/python3.5/site-packages/django/core/management/__init__.py", line 359, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/Users/jibreel/.Envs/eduwallets/lib/python3.5/site-packages/django/core/management/base.py", line 305, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/Users/jibl/.Envs/eduwallets/lib/python3.5/site-packages/django/core/management/base.py", line 353, in execute
    self.check()
  File "/Users/jibl/.Envs/eduwallets/lib/python3.5/site-packages/django/core/management/base.py", line 385, in check
    include_deployment_checks=include_deployment_checks,
  File "/Users/jibl/.Envs/eduwallets/lib/python3.5/site-packages/django/core/management/base.py", line 372, in _run_checks
    return checks.run_checks(**kwargs)
  File "/Users/jibl/.Envs/eduwallets/lib/python3.5/site-packages/django/core/checks/registry.py", line 81, in run_checks
    new_errors = check(app_configs=app_configs)
  File "/Users/jibl/.Envs/eduwallets/lib/python3.5/site-packages/django/contrib/auth/checks.py", line 114, in check_models_permissions
    max_builtin_permission_name_length = max(len(name) for name in builtin_permissions.values())
ValueError: max() arg is an empty sequence```

**Comment by spectras** [comment]
Hello,
Thanks for reporting. It looks like a bug indeed, though it might not be within hvad but, rather, hvad triggering it in the auth app. Either way I'll investigate and either fix it or escalate it depending on what I find.
I am low on time atm, but I'll do my best to look at that before tomorrow.

**Comment by spectras** [comment]
So, here is what I found: this is indeed a bug in Django, unrelated to hvad.
This bug has been introduced on April 6th, 2016 and fixed by commit [a8b8ef](https://github.com/django/django/commit/a8b8ef114dd01d9c1e71a620b732b9aac7b7da5c) on August 2nd, 2016.

Unfortunately, Django 1.10 was released on the first of August. This leaves but two options:
 1. Wait until the fix is included, in Django 1.10.1
 2. Use the git version of Django 1.10, that is, https://github.com/django/django/archive/stable/1.10.x.zip

I am sorry for the inconvenience. Thing is, as hvad generates models with empty default permissions (on purpose), it will not work with the unfixed version of Django.

**Comment by spaceexperiment** [comment]
I appreciate you took the time to look into it, i am in the development phase of a project and have switched to Django 1.9 for know,  will try out 1.10.1 when it's released.

Cheers

**Comment by spectras** [comment]
Issue #308 will track the evolution of this problem. You may subscribe to that one, I'll update it once it is fixed.

Thanks for taking the time to report here

**Comment by spectras** [comment]
Django 1.10.1 and hvad 1.6.0 are out, we should be back to normal.
