### ISSUE TITLE
django-booking, django 1.10, django-hvad 1.5.1

### ISSUE THREAD

**Issue by climb65** [KristianOellegaard/django-hvad#307]
Hello,

I have an issue that might come from django-hvad.
Here is my output when I run the following command:

python manage.py migrate booking

####################################  output begin
Traceback (most recent call last):
  File "manage.py", line 22, in <module>
    execute_from_command_line(sys.argv)
  File "/home/richard/programmation/python/django_projects/django_booking_env/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 367, in execute_from_command_line
    utility.execute()
  File "/home/richard/programmation/python/django_projects/django_booking_env/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 341, in execute
    django.setup()
  File "/home/richard/programmation/python/django_projects/django_booking_env/local/lib/python2.7/site-packages/django/__init__.py", line 27, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/home/richard/programmation/python/django_projects/django_booking_env/local/lib/python2.7/site-packages/django/apps/registry.py", line 108, in populate
    app_config.import_models(all_models)
  File "/home/richard/programmation/python/django_projects/django_booking_env/local/lib/python2.7/site-packages/django/apps/config.py", line 199, in import_models
    self.models_module = import_module(models_module_name)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/home/richard/programmation/python/django_projects/django_booking_env/local/lib/python2.7/site-packages/booking/models.py", line 14, in <module>
    class BookingStatus(TranslationModelMixin, TranslatableModel):
  File "/home/richard/programmation/python/django_projects/django_booking_env/local/lib/python2.7/site-packages/django/db/models/base.py", line 309, in __new__
    new_class._prepare()
  File "/home/richard/programmation/python/django_projects/django_booking_env/local/lib/python2.7/site-packages/django/db/models/base.py", line 359, in _prepare
    signals.class_prepared.send(sender=cls)
  File "/home/richard/programmation/python/django_projects/django_booking_env/local/lib/python2.7/site-packages/django/dispatch/dispatcher.py", line 191, in send
    response = receiver(signal=self, sender=sender, **named)
  File "/home/richard/programmation/python/django_projects/django_booking_env/local/lib/python2.7/site-packages/hvad/models.py", line 477, in prepare_translatable_model
    model.add_to_class('_base_manager', Manager())
  File "/home/richard/programmation/python/django_projects/django_booking_env/local/lib/python2.7/site-packages/django/db/models/base.py", line 316, in add_to_class
    value.contribute_to_class(cls, name)
  File "/home/richard/programmation/python/django_projects/django_booking_env/local/lib/python2.7/site-packages/django/db/models/manager.py", line 120, in contribute_to_class
    setattr(model, name, ManagerDescriptor(self))
AttributeError: can't set attribute
####################################  output end

pip list:

certifi (2016.8.8)
cffi (1.7.0)
cryptography (1.4)
Django (1.10)
django-booking (0.7.2)
django-countries (3.4.1)
django-hvad (1.5.1)
django-libs (1.67.5)
enum34 (1.1.6)
idna (2.1)
ipaddress (1.0.16)
ndg-httpsclient (0.4.2)
pip (8.1.2)
pyasn1 (0.1.9)
pycparser (2.14)
pyOpenSSL (16.0.0)
setuptools (18.2)
six (1.10.0)
urllib3 (1.16)
wheel (0.24.0)

Do you have an idea on how to solve this?
Should I downgrade django to 1.9?

Thanks very much for your help.

**Comment by spectras** [comment]
Hello, thanks for reporting here.

Django 1.10 was planned to be supported from hvad 1.6.0.
Unfortunately, a late-found bug in Django 1.10 makes it incompatible at the moment. It will be fixed in Django 1.10.1 (see #306 for details).
I chose to withhold the release of hvad 1.6.0 until Django 1.10.1 comes out.

At the moment, you may either:
 * Stick to Django 1.9, and wait for the fix in Django 1.10.1.
 * Use the git version of both, that is: https://github.com/django/django/archive/stable/1.10.x.zip and https://github.com/kristianoellegaard/django-hvad/tarball/master

I am sorry for the inconvenience.

**Comment by spectras** [comment]
Issue #308 will track the evolution of the migrate-to-django-1.10 problem. You may subscribe to that one, I'll update it once it is fixed.

Thanks for taking the time to report here.

**Comment by spectras** [comment]
Django 1.10.1 and hvad 1.6.0 are out, we should be back to normal.
