### ISSUE TITLE
WrongManager(Accessing translated fields like tag.name from an regular model requires a translation-aware queryset, obtained with the .language() method. For regular, non-translatable models, you can get one using hvad.utils.get_translation_aware_manager)

### ISSUE THREAD

**Issue by DmytroLitvinov** [KristianOellegaard/django-hvad#358]
Hello everyone.

I tried to integrate [django-taggit](https://github.com/jazzband/django-taggit) with django-hvad , but starting from version 0.19.0 I always get next error:

**Accessing translated fields like tag.name from an regular model requires a translation-aware queryset, obtained with the .language() method. For regular, non-translatable models, you can get one using hvad.utils.get_translation_aware_manager**

Django 1.11
Djangocms 3.6.0
Python 2
django-hvad 1.8.0
django-taggit>=0.19.0

**Full traceback:**
Internal Server Error: /admin/aldryn_news/news/add/
Traceback (most recent call last):
  File "/home/dmytro/.virtualenvs/gryps-project/local/lib/python2.7/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/home/dmytro/.virtualenvs/gryps-project/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/dmytro/.virtualenvs/gryps-project/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/dmytro/.virtualenvs/gryps-project/local/lib/python2.7/site-packages/django/utils/decorators.py", line 185, in inner
    return func(*args, **kwargs)
  File "/home/dmytro/.virtualenvs/gryps-project/local/lib/python2.7/site-packages/django/contrib/admin/options.py", line 552, in wrapper
    return self.admin_site.admin_view(view)(*args, **kwargs)
  File "/home/dmytro/.virtualenvs/gryps-project/local/lib/python2.7/site-packages/django/utils/decorators.py", line 149, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/home/dmytro/.virtualenvs/gryps-project/local/lib/python2.7/site-packages/django/views/decorators/cache.py", line 57, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "/home/dmytro/.virtualenvs/gryps-project/local/lib/python2.7/site-packages/django/contrib/admin/sites.py", line 224, in inner
    return view(request, *args, **kwargs)
  File "/home/dmytro/.virtualenvs/gryps-project/local/lib/python2.7/site-packages/django/contrib/admin/options.py", line 1509, in add_view
    return self.changeform_view(request, None, form_url, extra_context)
  File "/home/dmytro/.virtualenvs/gryps-project/local/lib/python2.7/site-packages/django/utils/decorators.py", line 67, in _wrapper
    return bound_func(*args, **kwargs)
  File "/home/dmytro/.virtualenvs/gryps-project/local/lib/python2.7/site-packages/django/utils/decorators.py", line 149, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/home/dmytro/.virtualenvs/gryps-project/local/lib/python2.7/site-packages/django/utils/decorators.py", line 63, in bound_func
    return func.__get__(self, type(self))(*args2, **kwargs2)
  File "/home/dmytro/.virtualenvs/gryps-project/local/lib/python2.7/site-packages/django/contrib/admin/options.py", line 1409, in changeform_view
    return self._changeform_view(request, object_id, form_url, extra_context)
  File "/home/dmytro/.virtualenvs/gryps-project/local/lib/python2.7/site-packages/django/contrib/admin/options.py", line 1450, in _changeform_view
    self.save_related(request, form, formsets, not add)
  File "/home/dmytro/.virtualenvs/gryps-project/local/lib/python2.7/site-packages/django/contrib/admin/options.py", line 1002, in save_related
    form.save_m2m()
  File "/home/dmytro/.virtualenvs/gryps-project/local/lib/python2.7/site-packages/django/forms/models.py", line 451, in _save_m2m
    f.save_form_data(self.instance, cleaned_data[f.name])
  File "/home/dmytro/.virtualenvs/gryps-project/local/lib/python2.7/site-packages/taggit/managers.py", line 551, in save_form_data
    getattr(instance, self.name).set(*value)
  File "/home/dmytro/.virtualenvs/gryps-project/local/lib/python2.7/site-packages/taggit/utils.py", line 153, in inner
    return func(self, *args, **kwargs)
  File "/home/dmytro/.virtualenvs/gryps-project/local/lib/python2.7/site-packages/taggit/managers.py", line 282, in set
    .values_list('tag__name', flat=True))
  File "/home/dmytro/.virtualenvs/gryps-project/local/lib/python2.7/site-packages/django/db/models/query.py", line 722, in values_list
    clone = self._values(*_fields, **expressions)
  File "/home/dmytro/.virtualenvs/gryps-project/local/lib/python2.7/site-packages/django/db/models/query.py", line 695, in _values
    clone.query.set_values(fields)
  File "/home/dmytro/.virtualenvs/gryps-project/local/lib/python2.7/site-packages/django/db/models/sql/query.py", line 1896, in set_values
    self.add_fields(field_names, True)
  File "/home/dmytro/.virtualenvs/gryps-project/local/lib/python2.7/site-packages/django/db/models/sql/query.py", line 1645, in add_fields
    name.split(LOOKUP_SEP), opts, alias, allow_many=allow_m2m)
  File "/home/dmytro/.virtualenvs/gryps-project/local/lib/python2.7/site-packages/django/db/models/sql/query.py", line 1417, in setup_joins
    names, opts, allow_many, fail_on_missing=True)
  File "/home/dmytro/.virtualenvs/gryps-project/local/lib/python2.7/site-packages/django/db/models/sql/query.py", line 1309, in names_to_path
    field = opts.get_field(name)
  File "/home/dmytro/.virtualenvs/gryps-project/local/lib/python2.7/site-packages/hvad/utils.py", line 128, in __call__
    raise WrongManager(meta, name)
WrongManager: Accessing translated fields like tag.name from an regular model requires a translation-aware queryset, obtained with the .language() method. For regular, non-translatable models, you can get one using hvad.utils.get_translation_aware_manager

**Comment by DmytroLitvinov** [comment]
Hi @spectras .

Any chance that you could give feedback on that where I could investigate?
I found related issue https://github.com/KristianOellegaard/django-hvad/issues/286, but it was closed due to inactivity, unfortunately.

**Comment by icu0755** [comment]
I had a similar issue with #286 in django admin with `TranslatableTabularInline` class and `fields` containing translatable field.

It is not possible to get translatable field with `get_field(field_name)` from the main model at the moment.
Due to the fact that `SmartGetField` will always throw an exception not matter if you use an object, translatable object or the model class itself.

```
        try:
            return self.real(name, *args, **kwargs)
        except FieldDoesNotExist as e:
            try:
                meta.translations_model._meta.get_field(name, *args, **kwargs)
            except FieldDoesNotExist:
                raise e
            else:
                raise WrongManager(meta, name)
```

**Comment by DmytroLitvinov** [comment]
Resolved my issue with providing custom `TaggableManager` where I have rewritten next methods: `set` and `remove`. Needed to get `name` thought translate DB.
